name: bubble_tab_indicator
description: A Flutter library to add bubble tab indicator to TabBar
version: 0.1.3
author: Vipul Asri <vipulasri.2007@gmail.com>
homepage: https://github.com/vipulasri/flutter_bubble_tab_indicator

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=1.23.0 <3.0.0'